FROM 551163406316.dkr.ecr.us-west-2.amazonaws.com/baseimage:2

RUN apt-get update
RUN apt-get install software-properties-common wget -y
RUN add-apt-repository ppa:openjdk-r/ppa -y
RUN apt-get update
RUN apt-get install openjdk-8-jdk -y
RUN wget NEXUS_URL_JENKINS -P /opt/jenkins.war
RUN chmod 644 /opt/jenkins.war
ENV JENKINS_HOME /jenkins

ENTRYPOINT ["java", "-jar", "/opt/jenkins.war"]
EXPOSE 8080
CMD [""]
